window.INVENTORY_CONFIG = {
  MODE: 'gas',
  API_URL: 'PASTE_YOUR_GOOGLE_APPS_SCRIPT_WEB_APP_EXEC_URL_HERE',
  APP_NAME: 'BHH Rx Inventory',
  HOSPITAL_NAME: 'Bangkok Hospital Hatyai',
  LOGO_URL: '',
  IDLE_TIMEOUT_MS: 30 * 60 * 1000,
  SYNC_INTERVAL_MS: 15000,
  TRANSACTION_LIMIT: 1200
};
